"""Update datetime defaults to use timezone-aware datetime.now(timezone.utc)

Revision ID: 88d971444af5
Revises: d85e468ad428
Create Date: 2025-12-24 14:38:36.404396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d971444af5'
down_revision: Union[str, None] = 'd85e468ad428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
